image: archlinux
packages:
  - rustup
  - mingw-w64-gcc  # for windows build linker stage
  - hut
sources:
  - https://git.sr.ht/~grandchild/avs-preset-depends
oauth: pages.sr.ht/PAGES:RW
environment:
  docsite: grandchild.srht.site

tasks:
  - setup: |
      rustup default stable
      rustup target add x86_64-unknown-linux-gnu
      rustup target add x86_64-pc-windows-gnu
  - check: |
      cd avs-preset-depends
      rustfmt --check **/*.rs
      cargo clippy
  - test: |
      cd avs-preset-depends
      cargo test
  - build-linux: |
      cd avs-preset-depends
      cargo b --release --target x86_64-unknown-linux-gnu
      mv target/x86_64-unknown-linux-gnu/release/preset-depends ../
  - build-windows: |
      cd avs-preset-depends
      cargo b --release --target x86_64-pc-windows-gnu
      mv target/x86_64-pc-windows-gnu/release/preset-depends.exe ../
  - publish-docs: |
      cd avs-preset-depends
      cargo doc --document-private-items --no-deps
      cd target/doc/
      tar -cvz . > ../docs.tar.gz
      hut pages publish -d $docsite ../docs.tar.gz
artifacts:
  - preset-depends
  - preset-depends.exe
