[package]
name = "preset-depends"
version = "0.2.0"
edition = "2021"

[dependencies]
argh = "0"
rayon = "1"

[profile.release]
strip = true
lto = true
opt-level = "z"  # Optimize for size
# panic = "abort"  # ~8kB size reduction
