max_width = 88

# Comment-wrapping isn't stable yet, and turning wrap_comments on
# doesn't actually make rustfmt wrap the comments but still leads
# to false rustfmt check errors.
#wrap_comments = true
#comment_width = 88

use_small_heuristics = "Off"
fn_call_width = 88
attr_fn_like_width = 88
struct_lit_width = 88
struct_variant_width = 88
array_width = 88
chain_width = 88
single_line_if_else_max_width = 88
