name: Check, Build and Upload

on:
  push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: rustfmt
        run: rustfmt **/*.rs
      - name: clippy
        run: cargo clippy -- -Dwarnings
  build-linux:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: build
        run: |
          cargo build --release
          mv target/release/preset-depends ./preset-depends_linux
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: preset-depends_linux
          path: preset-depends_linux
  build-windows:
    runs-on: windows-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: build
        run: |
          cargo build --release
          mv target/release/preset-depends.exe ./preset-depends_windows.exe
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: preset-depends_windows
          path: preset-depends_windows.exe
